# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170317_1000'),
    ]

    operations = [
    ]
